apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: lbwreg-content
spec:
  selector:
    matchLabels:
      k8s-app: lbwreg-content
  template:
    metadata:
      labels:
        k8s-app: lbwreg-content
    spec:
      containers:
      - name: nginx
        image: nginx:1
        env:
        - name: NGINX_HOST
          value: content.draiocht.net
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: content
      volumes:
        - name: content
          persistentVolumeClaim:
            claimName: lbwreg-content
