apiVersion: v1
kind: Secret
metadata:
  name: mariadb-root-pass
type: Opaque
data:
  password: $(echo -n ROOT_PASS | base64)
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-credentials
type: Opaque
data:
  user: $(echo -n DB_USER | base64)
  password: $(echo -n DB_PASS | base64)
