---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: smokeping
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    k8s-app: smokeping
spec:
  tls:
    - secretName: "smokeping-tls"
  rules:
    - host: "smokeping.k.draiocht.net"
      http:
        paths:
          - path: /
            backend:
              serviceName: smokeping
              servicePort: web
